### ISSUE TITLE
✅ Final Project Feedback

### ISSUE THREAD

**Issue by cmota** [sc0des/mobile-app#1]
Hello 👋,

Well done! Keep up the excellent work! 🙌

Looking forward to a link to the app on the Google Play Store so I can install your app 😛

Really happy with how you've developed the app! The UI is perfect and the code is really well structured - congratulations!

### Grade

90/100

### Suggestions for improvement

* I've tried to search for _anything unique_ and I noticed that you're not adding the text to the text field

* You can remove all the unused imports by going to the status bar and click on Code > Optimize Imports.

* The same thing is valid for code that you're not using, you can remove it; there's always git history 🙂

**Comment by sc0des** [comment]
Thank you for the lovely feedback 🙂. I will share the link once I release my app on Google Play Store.
